// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_and_export_cpp
Rcpp::List generate_and_export_cpp(Rcpp::List population_attrs, Rcpp::NumericVector birth_nums, Rcpp::CharacterVector patient_ids, double t_end, Rcpp::IntegerVector seeds, SEXP modules_xptr);
RcppExport SEXP _rsynthea_generate_and_export_cpp(SEXP population_attrsSEXP, SEXP birth_numsSEXP, SEXP patient_idsSEXP, SEXP t_endSEXP, SEXP seedsSEXP, SEXP modules_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type population_attrs(population_attrsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type birth_nums(birth_numsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type patient_ids(patient_idsSEXP);
    Rcpp::traits::input_parameter< double >::type t_end(t_endSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type modules_xptr(modules_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_and_export_cpp(population_attrs, birth_nums, patient_ids, t_end, seeds, modules_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
int rcpp_hello(int x);
RcppExport SEXP _rsynthea_rcpp_hello(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_hello(x));
    return rcpp_result_gen;
END_RCPP
}
// compile_all_modules
SEXP compile_all_modules(Rcpp::List modules_r);
RcppExport SEXP _rsynthea_compile_all_modules(SEXP modules_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type modules_r(modules_rSEXP);
    rcpp_result_gen = Rcpp::wrap(compile_all_modules(modules_r));
    return rcpp_result_gen;
END_RCPP
}
// inspect_compiled_modules
Rcpp::DataFrame inspect_compiled_modules(SEXP ptr_sexp);
RcppExport SEXP _rsynthea_inspect_compiled_modules(SEXP ptr_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_sexp(ptr_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(inspect_compiled_modules(ptr_sexp));
    return rcpp_result_gen;
END_RCPP
}
// inspect_delays
Rcpp::DataFrame inspect_delays(SEXP ptr_sexp, std::string module_name);
RcppExport SEXP _rsynthea_inspect_delays(SEXP ptr_sexpSEXP, SEXP module_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_sexp(ptr_sexpSEXP);
    Rcpp::traits::input_parameter< std::string >::type module_name(module_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(inspect_delays(ptr_sexp, module_name));
    return rcpp_result_gen;
END_RCPP
}
// simulate_patient_cpp
Rcpp::List simulate_patient_cpp(Rcpp::List attributes_r, double birth_num, double t_end, int seed, SEXP modules_xptr);
RcppExport SEXP _rsynthea_simulate_patient_cpp(SEXP attributes_rSEXP, SEXP birth_numSEXP, SEXP t_endSEXP, SEXP seedSEXP, SEXP modules_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type attributes_r(attributes_rSEXP);
    Rcpp::traits::input_parameter< double >::type birth_num(birth_numSEXP);
    Rcpp::traits::input_parameter< double >::type t_end(t_endSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type modules_xptr(modules_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_patient_cpp(attributes_r, birth_num, t_end, seed, modules_xptr));
    return rcpp_result_gen;
END_RCPP
}
// simulate_population_cpp
Rcpp::DataFrame simulate_population_cpp(Rcpp::List population_attrs, Rcpp::NumericVector birth_nums, double t_end, Rcpp::IntegerVector seeds, SEXP modules_xptr);
RcppExport SEXP _rsynthea_simulate_population_cpp(SEXP population_attrsSEXP, SEXP birth_numsSEXP, SEXP t_endSEXP, SEXP seedsSEXP, SEXP modules_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type population_attrs(population_attrsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type birth_nums(birth_numsSEXP);
    Rcpp::traits::input_parameter< double >::type t_end(t_endSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type modules_xptr(modules_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_population_cpp(population_attrs, birth_nums, t_end, seeds, modules_xptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsynthea_generate_and_export_cpp", (DL_FUNC) &_rsynthea_generate_and_export_cpp, 6},
    {"_rsynthea_rcpp_hello", (DL_FUNC) &_rsynthea_rcpp_hello, 1},
    {"_rsynthea_compile_all_modules", (DL_FUNC) &_rsynthea_compile_all_modules, 1},
    {"_rsynthea_inspect_compiled_modules", (DL_FUNC) &_rsynthea_inspect_compiled_modules, 1},
    {"_rsynthea_inspect_delays", (DL_FUNC) &_rsynthea_inspect_delays, 2},
    {"_rsynthea_simulate_patient_cpp", (DL_FUNC) &_rsynthea_simulate_patient_cpp, 5},
    {"_rsynthea_simulate_population_cpp", (DL_FUNC) &_rsynthea_simulate_population_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsynthea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
