# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_and_export_cpp <- function(population_attrs, birth_nums, patient_ids, t_end, seeds, modules_xptr) {
    .Call(`_rsynthea_generate_and_export_cpp`, population_attrs, birth_nums, patient_ids, t_end, seeds, modules_xptr)
}

rcpp_hello <- function(x) {
    .Call(`_rsynthea_rcpp_hello`, x)
}

compile_all_modules <- function(modules_r) {
    .Call(`_rsynthea_compile_all_modules`, modules_r)
}

inspect_compiled_modules <- function(ptr_sexp) {
    .Call(`_rsynthea_inspect_compiled_modules`, ptr_sexp)
}

inspect_delays <- function(ptr_sexp, module_name) {
    .Call(`_rsynthea_inspect_delays`, ptr_sexp, module_name)
}

simulate_patient_cpp <- function(attributes_r, birth_num, t_end, seed, modules_xptr) {
    .Call(`_rsynthea_simulate_patient_cpp`, attributes_r, birth_num, t_end, seed, modules_xptr)
}

simulate_population_cpp <- function(population_attrs, birth_nums, t_end, seeds, modules_xptr) {
    .Call(`_rsynthea_simulate_population_cpp`, population_attrs, birth_nums, t_end, seeds, modules_xptr)
}

